image: node:12.18.3

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@8.3.4
  - npm install
  - ng build
  - mv dist/infinite-scroller/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - pages